syntax = "proto3";
option java_multiple_files = true;
option java_package = "com.mycompany.smartzerohungersystem.foodinventory";
package com.mycompany.smartzerohungersystem.foodinventory;

import "google/protobuf/empty.proto";

message AddItemRequest {
  string name     = 1;
  int32  quantity = 2;
}

message AddItemResponse {
  string message = 1;
}

message InventoryItem {
  string name     = 1;
  int32  quantity = 2;
}

message InventoryList {
  repeated InventoryItem items = 1;
}

service FoodInventoryService {
  rpc AddItem     (AddItemRequest) returns (AddItemResponse);
  rpc GetInventory (google.protobuf.Empty)         returns (InventoryList);
}

